// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/listar-fontes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/lib/datasets.ts
var BASE = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRmWTBTuo3l7yKebZuk-qJxQfpG_qvoKSHK6_DxSmaV0cT_iKHZQkZLAakrvYeDPh1oe20_vlOJJ7ex/pub?gid=";
var DATASETS = [
  {
    id: "b1_primeira_consulta",
    titulo: "B1 \u2014 1\xAA Consulta Odontol\xF3gica",
    descricao: "Pacientes individuais com/sem primeira consulta odontol\xF3gica program\xE1tica.",
    gid: "424984913"
  },
  {
    id: "b1_denominador",
    titulo: "B1 \u2014 Denominador (popula\xE7\xE3o)",
    descricao: "Popula\xE7\xE3o de refer\xEAncia por equipe usada como denominador do indicador B1.",
    gid: "2062770567"
  },
  {
    id: "b2_tratamento",
    titulo: "B2 \u2014 Tratamento Odontol\xF3gico Conclu\xEDdo",
    descricao: "Pacientes individuais e situa\xE7\xE3o do tratamento odontol\xF3gico.",
    gid: "929511633"
  },
  {
    id: "b3_exodontias",
    titulo: "B3 \u2014 Taxa de Exodontias",
    descricao: "Dados agregados mensais de exodontias por equipe.",
    gid: "1259472924"
  },
  {
    id: "b4_escovacao",
    titulo: "B4 \u2014 Escova\xE7\xE3o Dental Supervisionada",
    descricao: "Dados agregados mensais de escova\xE7\xE3o supervisionada por equipe.",
    gid: "506888516"
  },
  {
    id: "b5_preventivos",
    titulo: "B5 \u2014 Procedimentos Odontol\xF3gicos Preventivos",
    descricao: "Dados agregados mensais de procedimentos preventivos por equipe.",
    gid: "987145384"
  },
  {
    id: "b6_art",
    titulo: "B6 \u2014 Tratamento Restaurador Atraum\xE1tico (ART)",
    descricao: "Dados agregados mensais de ART por equipe.",
    gid: "1896101952"
  },
  {
    id: "dados_oficiais",
    titulo: "Dados oficiais (consolidado)",
    descricao: "Valores oficiais por m\xEAs/equipe. Quando existe linha oficial, ela prevalece sobre o preliminar, mesmo se zerada.",
    gid: "533321977"
  }
];
var getDataset = (id) => DATASETS.find((d) => d.id === id);
var datasetUrl = (d) => `${BASE}${d.gid}&single=true&output=csv&_=${Date.now()}`;

// src/lib/mcp/tools/listar-fontes.ts
var listar_fontes_default = defineTool({
  name: "listar_fontes",
  title: "Listar fontes de dados",
  description: "Lista as fontes de dados (indicadores B1 a B6 e consolidado oficial) dispon\xEDveis no painel de Sa\xFAde Bucal de Varjota.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: DATASETS.map((d) => `- ${d.id}: ${d.titulo} \u2014 ${d.descricao}`).join("\n")
      }
    ],
    structuredContent: {
      fontes: DATASETS.map(({ id, titulo, descricao }) => ({ id, titulo, descricao }))
    }
  })
});

// src/lib/mcp/tools/consultar-dados.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/lib/csv.ts
var parseCsvLine = (line) => {
  const out = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (quoted && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else quoted = !quoted;
    } else if (ch === "," && !quoted) {
      out.push(cur.trim());
      cur = "";
    } else cur += ch;
  }
  out.push(cur.trim());
  return out;
};
var parseCsv = (text) => {
  const clean = text.replace(/^\uFEFF/, "").replace(/\r/g, "");
  const lines = clean.split("\n").filter((l) => l.trim() !== "");
  if (lines.length === 0) return { headers: [], rows: [] };
  const headers = parseCsvLine(lines[0]);
  const rows = lines.slice(1).map((line) => {
    const cols = parseCsvLine(line);
    const row = {};
    headers.forEach((h, i) => {
      row[h] = cols[i] ?? "";
    });
    return row;
  });
  return { headers, rows };
};
var fetchCsv = async (url) => {
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`Falha ao buscar planilha (HTTP ${res.status})`);
  return parseCsv(await res.text());
};
var norm = (v) => (v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/\besf\b/g, "esb").trim();

// src/lib/mcp/tools/consultar-dados.ts
var consultar_dados_default = defineTool2({
  name: "consultar_dados",
  title: "Consultar dados de um indicador",
  description: "Retorna as linhas de uma fonte de dados do painel (ex.: b1_primeira_consulta, b5_preventivos). Permite filtrar por equipe, micro\xE1rea ou m\xEAs e limitar a quantidade de linhas.",
  inputSchema: {
    fonte: z.string().describe(`Id da fonte. Valores v\xE1lidos: ${DATASETS.map((d) => d.id).join(", ")}`),
    equipe: z.string().optional().describe("Filtro parcial por equipe (ESB/ESF s\xE3o equivalentes)."),
    microarea: z.string().optional().describe("Filtro parcial por micro\xE1rea."),
    mes: z.string().optional().describe("Filtro parcial por m\xEAs de refer\xEAncia."),
    limite: z.number().int().min(1).max(500).optional().describe("M\xE1ximo de linhas (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ fonte, equipe, microarea, mes, limite }) => {
    const ds = getDataset(fonte);
    if (!ds) {
      return {
        content: [
          {
            type: "text",
            text: `Fonte desconhecida: ${fonte}. Use listar_fontes para ver as op\xE7\xF5es.`
          }
        ],
        isError: true
      };
    }
    try {
      const { headers, rows } = await fetchCsv(datasetUrl(ds));
      const findCol = (needles) => headers.find((h) => needles.some((n) => norm(h).includes(n)));
      const colEquipe = findCol(["equipe", "esb", "esf"]);
      const colMicro = findCol(["microarea", "micro area", "area"]);
      const colMes = findCol(["mes", "referencia", "competencia"]);
      const matches = (row, col, value) => !value || (col ? norm(row[col]).includes(norm(value)) : false);
      const filtered = rows.filter(
        (r) => matches(r, colEquipe, equipe) && matches(r, colMicro, microarea) && matches(r, colMes, mes)
      );
      const max = limite ?? 100;
      const page = filtered.slice(0, max);
      return {
        content: [
          {
            type: "text",
            text: `${ds.titulo} \u2014 ${filtered.length} linha(s) ap\xF3s filtro (exibindo ${page.length}).
Colunas: ${headers.join(" | ")}

` + page.map((r) => headers.map((h) => r[h]).join(" | ")).join("\n")
          }
        ],
        structuredContent: {
          fonte: ds.id,
          titulo: ds.titulo,
          colunas: headers,
          total: filtered.length,
          exibindo: page.length,
          linhas: page
        }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Erro ao consultar dados: ${String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/listar-equipes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var listar_equipes_default = defineTool3({
  name: "listar_equipes",
  title: "Listar equipes",
  description: "Lista as equipes (ESB) encontradas em uma fonte de dados do painel, com a contagem de linhas de cada uma.",
  inputSchema: {
    fonte: z2.string().default("b1_primeira_consulta").describe(`Id da fonte. Valores v\xE1lidos: ${DATASETS.map((d) => d.id).join(", ")}`)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ fonte }) => {
    const ds = getDataset(fonte);
    if (!ds) {
      return {
        content: [{ type: "text", text: `Fonte desconhecida: ${fonte}.` }],
        isError: true
      };
    }
    try {
      const { headers, rows } = await fetchCsv(datasetUrl(ds));
      const colEquipe = headers.find((h) => ["equipe", "esb", "esf"].some((n) => norm(h).includes(n)));
      if (!colEquipe) {
        return {
          content: [
            { type: "text", text: `A fonte ${ds.titulo} n\xE3o possui coluna de equipe.` }
          ],
          isError: true
        };
      }
      const counts = /* @__PURE__ */ new Map();
      for (const r of rows) {
        const nome = (r[colEquipe] ?? "").replace(/\bESF\b/gi, "ESB").trim();
        if (!nome) continue;
        counts.set(nome, (counts.get(nome) ?? 0) + 1);
      }
      const equipes = [...counts.entries()].map(([equipe, linhas]) => ({ equipe, linhas })).sort((a, b) => a.equipe.localeCompare(b.equipe));
      return {
        content: [
          {
            type: "text",
            text: `Equipes em ${ds.titulo}:
` + equipes.map((e) => `- ${e.equipe} (${e.linhas} linhas)`).join("\n")
          }
        ],
        structuredContent: { fonte: ds.id, equipes }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Erro ao listar equipes: ${String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/listar-pendencias.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var isPendente = (valor) => {
  const v = norm(valor);
  if (!v) return true;
  return !(v.includes("sim") || v.includes("conclu") || v.includes("realizad") || v.includes("finaliz"));
};
var listar_pendencias_default = defineTool4({
  name: "listar_pendencias",
  title: "Listar pend\xEAncias por equipe",
  description: "Lista pacientes pendentes de uma equipe: B1 (sem 1\xAA consulta odontol\xF3gica) ou B2 (tratamento odontol\xF3gico n\xE3o conclu\xEDdo).",
  inputSchema: {
    indicador: z3.enum(["b1", "b2"]).describe("b1 = sem 1\xAA consulta; b2 = tratamento pendente."),
    equipe: z3.string().min(1).describe("Nome (ou parte) da equipe, ex.: 'Acampamento'."),
    limite: z3.number().int().min(1).max(500).optional().describe("M\xE1ximo de pacientes (padr\xE3o 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ indicador, equipe, limite }) => {
    const ds = getDataset(indicador === "b1" ? "b1_primeira_consulta" : "b2_tratamento");
    if (!ds) {
      return { content: [{ type: "text", text: "Fonte indispon\xEDvel." }], isError: true };
    }
    try {
      const { headers, rows } = await fetchCsv(datasetUrl(ds));
      const find = (needles) => headers.find((h) => needles.some((n) => norm(h).includes(n)));
      const colEquipe = find(["equipe", "esb", "esf"]);
      const colNome = find(["nome", "paciente", "cidadao"]);
      const colMicro = find(["microarea", "micro area", "area"]);
      const colStatus = indicador === "b1" ? find(["1a consulta", "primeira consulta", "consulta", "situacao", "status"]) : find(["tratamento", "situacao", "status", "conclu"]);
      const daEquipe = rows.filter((r) => colEquipe ? norm(r[colEquipe]).includes(norm(equipe)) : false);
      const pendentes = daEquipe.filter((r) => colStatus ? isPendente(r[colStatus]) : false);
      const max = limite ?? 200;
      const lista = pendentes.slice(0, max).map((r) => ({
        nome: colNome ? r[colNome] : "",
        microarea: colMicro ? r[colMicro] : "",
        equipe: colEquipe ? (r[colEquipe] ?? "").replace(/\bESF\b/gi, "ESB") : "",
        situacao: colStatus ? r[colStatus] : ""
      }));
      lista.sort(
        (a, b) => a.microarea.localeCompare(b.microarea) || a.nome.localeCompare(b.nome)
      );
      return {
        content: [
          {
            type: "text",
            text: `${ds.titulo} \u2014 equipe "${equipe}": ${daEquipe.length} pacientes, ${pendentes.length} pendentes (exibindo ${lista.length}).

` + lista.map((p) => `- MA ${p.microarea} | ${p.nome} | ${p.situacao}`).join("\n")
          }
        ],
        structuredContent: {
          indicador,
          equipe,
          total_equipe: daEquipe.length,
          total_pendentes: pendentes.length,
          pendentes: lista
        }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Erro ao listar pend\xEAncias: ${String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/explicar-indicadores.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var PARAMETROS = [
  {
    indicador: "B1 \u2014 1\xAA Consulta Odontol\xF3gica",
    parametros: "Regular \u2264 0,25% | Suficiente 0,25\u20130,75% | Bom 0,75\u20131,25% | \xD3timo > 1,25%"
  },
  {
    indicador: "B2 \u2014 Tratamento Odontol\xF3gico Conclu\xEDdo",
    parametros: "Percentual de tratamentos conclu\xEDdos sobre 1\xAA consultas."
  },
  {
    indicador: "B3 \u2014 Taxa de Exodontias",
    parametros: "\xD3timo \u22653% e <10% | Bom \u226510% e <12% | Suficiente \u226512% e <14% | Regular <3% ou \u226514%"
  },
  {
    indicador: "B4 \u2014 Escova\xE7\xE3o Dental Supervisionada",
    parametros: "Percentual de cobertura da popula\xE7\xE3o por escova\xE7\xE3o supervisionada."
  },
  {
    indicador: "B5 \u2014 Procedimentos Odontol\xF3gicos Preventivos",
    parametros: "Suficiente \u226540% e <55% | Bom \u226555% e <65% | \xD3timo \u226565% e \u226485%"
  },
  {
    indicador: "B6 \u2014 Tratamento Restaurador Atraum\xE1tico (ART)",
    parametros: "Bom > 6% | \xD3timo > 8%"
  }
];
var explicar_indicadores_default = defineTool5({
  name: "explicar_indicadores",
  title: "Explicar indicadores e par\xE2metros",
  description: "Explica os indicadores B1 a B6 do painel de Sa\xFAde Bucal de Varjota, seus conceitos (Regular, Suficiente, Bom, \xD3timo) e a divis\xE3o em quadrimestres.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: PARAMETROS.map((p) => `${p.indicador}
  ${p.parametros}`).join("\n\n") + "\n\nQuadrimestres: 1\xBA (jan\u2013abr), 2\xBA (mai\u2013ago), 3\xBA (set\u2013dez).\nQuando existe dado oficial para m\xEAs/equipe, ele prevalece sobre o preliminar, mesmo se zerado."
      }
    ],
    structuredContent: { indicadores: PARAMETROS }
  })
});

// src/lib/mcp/index.ts
var projectRef = "awvhspvzuvvgokidskcb";
var mcp_default = defineMcp({
  name: "saude-bucal-varjota-mcp",
  title: "Sa\xFAde Bucal Varjota",
  version: "0.1.0",
  instructions: "Ferramentas do painel de Indicadores de Sa\xFAde Bucal de Varjota. Use listar_fontes para descobrir as bases, explicar_indicadores para entender os par\xE2metros B1\u2013B6, consultar_dados para ler linhas de uma base, listar_equipes para ver as equipes (ESB) e listar_pendencias para pacientes pendentes de 1\xAA consulta (B1) ou tratamento (B2).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [listar_fontes_default, explicar_indicadores_default, consultar_dados_default, listar_equipes_default, listar_pendencias_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
